import { ShardState } from "@/features/cms/shards/enums/ShardState";
import { ShardType } from "@/features/cms/shards/enums/ShardType";
import { IShards } from "@/features/cms/shards/types/IShards";
import { SplinterCategory } from "@/features/splinters/enums/SplinterCategory";

// For dawnshards endpoint:
// {
//   category: SplinterCategory.Dawnshard,
//   id: "change",
//   name: "Change",
//   state: SplinterState.Alive,
//   vessel: "rysn",
// },
// {
//   category: SplinterCategory.Dawnshard,
//   id: "life",
//   name: "Life",
//   slivers: ["hoid"],
// },

export const data: IShards = {
  shards: [
    {
      category: SplinterCategory.Shard,
      id: "adonalsium",
      name: "Adonalsium",
      type: ShardType.Omegashard,
      state: ShardState.Splintered,
      splitsInto: [
        "autonomy",
        "ambition",
        "cultivation",
        "devotion",
        "dominion",
        "endowment",
        "honor",
        "invention",
        "mercy",
        "odium",
        "preservation",
        "ruin",
        "valor",
        "whimsy",
        "unknown1",
        "unknown2",
      ],
    },
    {
      category: SplinterCategory.Shard,
      id: "autonomy",
      name: "Autonomy",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "ambition",
      name: "Ambition",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "cultivation",
      name: "Cultivation",
      type: ShardType.Shard,
      state: ShardState.Alive,
      vessel: "koravellium-avast",
    },
    {
      category: SplinterCategory.Shard,
      id: "devotion",
      name: "Devotion",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "dominion",
      name: "Dominion",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "endowment",
      name: "Endowment",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "honor",
      name: "Honor",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "invention",
      name: "Invention",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "mercy",
      name: "Mercy",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "odium",
      name: "Odium",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "preservation",
      name: "Preservation",
      type: ShardType.Shard,
      state: ShardState.Combined,
      combinesInto: {
        harmony: ["preservation", "ruin"],
      },
      slivers: ["kelsier", "the-lord-ruler"],
    },
    {
      category: SplinterCategory.Shard,
      id: "ruin",
      name: "Ruin",
      type: ShardType.Shard,
      state: ShardState.Combined,
      combinesInto: {
        harmony: ["preservation", "ruin"],
      },
    },
    {
      category: SplinterCategory.Shard,
      id: "valor",
      name: "Valor",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "whimsy",
      name: "Whimsy",
      type: ShardType.Shard,
      state: ShardState.Splintered,
    },
    {
      category: SplinterCategory.Shard,
      id: "unknown1",
      name: "UNKNOWN 1",
      type: ShardType.Shard,
    },
    {
      category: SplinterCategory.Shard,
      id: "unknown2",
      name: "UNKNOWN 2",
      type: ShardType.Shard,
    },
  ],
};
